### ISSUE TITLE
Plugin description cannot be edited.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone/kintone-cli#13]
Can't find a place to describe the plugin.
The description seems to be fixed in "Kintone Plugin".

**Comment by r3-yamauchi** [comment]
https://github.com/kintone/kintone-cli/blob/master/src/commands/Build/builder.ts#L27
の内容を確認して試したところ、 config.json の "uploadConfig" 内に
```
        "description": {
            "ja": "これはサンプルプラグインです。",
            "en": "This is sample plugin.",
            "zh": "这是插件的例子"
        },
```
を追加すると manifest.json に反映されました。

もし、`kintone-cli create-template` コマンドにより生成される config.json に "description" を含めるようにしたいのであれば
https://github.com/kintone/kintone-cli/blob/master/src/commands/Initialize/generator.ts#L197
以下に
```
manifestJSON['uploadConfig']['description'] = {
    'ja': 'これはサンプルプラグインです。',
    'en': 'This is sample plugin.',
    'zh': '这是插件的例子'
}
```
を入れるようなプルリクを送ってみてはいかがかと思います。

**Comment by Yanchi4425** [comment]
@r3-yamauchi 
ありがとうございます！
ご教示いただいたやり方でうまくいきました。
また、nameやversionも同じように追加できることも確認できました。
