### ISSUE TITLE
Source map is not created when the "dev" command.

### ISSUE THREAD

**Issue by Yanchi4425** [kintone/kintone-cli#25]
In the current version, the source map does not seem to be output when the "dev" command is executed.
This happens with both customizations and plugins.

Also, I would also like the plugin's config.js to output a source map as well.

**Comment by youtr-s** [comment]
Thank you for registering the issue.
In the current version, map file is not made by default.
So if you want it, would you please to modify the package.json in a kintone-cli project as following ?
- before: `"build-${appname}": "webpack --mode production --config ${appname}/webpack.config.js"` 
- after: `"build-${appname}": "webpack --mode development --config ${appname}/webpack.config.js"` 

Thank you.

**Comment by Yanchi4425** [comment]
I've tried it on multiple platforms, and none of them created a MAP file.

In future updates, will it be created while the dev command is running?

**Comment by Yanchi4425** [comment]
Hi.
I tried writing it like the old version, and now it outputs a source map.

```
// before
"build-Hoge": "webpack --mode development --config Hoge/webpack.config.js"

// after
"build-Hoge": "webpack --config Hoge/webpack.config.js"
```

**Comment by youtr-s** [comment]
Sorry to late reply.
I confirmed that it is success to make map file by your setting.
This problem seems that caused by various factors and it needs more time to make an appropriate correction.
So would you please to use kintone-cli like above usage for a while?
Thank you.
